import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Link, Navigate, Route, Routes, useNavigate} from 'react-router-dom';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
export const supabase = createClient(supabaseUrl || 'https://placeholder.supabase.co', supabaseKey || 'placeholder');

function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function discount(oldP,p){if(!oldP||Number(oldP)<=Number(p)) return null; return Math.round((1-Number(p)/Number(oldP))*100);}

function Header({admin=false}){
  const nav=useNavigate();
  async function logout(){await supabase.auth.signOut();nav('/painel');}
  return <header className="top"><div className="brand"><img src="/logo.jpg"/><div><b>Achadinhos Diários</b><span>Os melhores achadinhos, todo dia!</span></div></div>{admin && <button className="btn ghost" onClick={logout}>Sair</button>}</header>
}

function PublicHome(){
 const [products,setProducts]=useState([]); const [loading,setLoading]=useState(true); const [q,setQ]=useState('');
 useEffect(()=>{load();},[]);
 async function load(){const {data,error}=await supabase.from('products').select('*').eq('active',true).order('created_at',{ascending:false}); if(!error)setProducts(data||[]); setLoading(false);}
 const filtered=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())||p.description?.toLowerCase().includes(q.toLowerCase())),[products,q]);
 return <><Header/><main className="public"><section className="hero"><div><div className="pill">🔥 ACHADINHOS DO DIA</div><h1>Ofertas que valem a pena.</h1><p>Produtos selecionados, preços especiais e links diretos para comprar.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 Buscar produto..."/></div><img className="hero-logo" src="/logo.jpg"/></section><div className="section-title"><div><h2>Achadinhos recentes</h2><p>Confira as ofertas disponíveis.</p></div><span>{filtered.length} produto(s)</span></div>{loading?<div className="empty">Carregando ofertas...</div>:filtered.length===0?<div className="empty">Nenhum produto encontrado.</div>:<div className="grid">{filtered.map(p=><ProductCard key={p.id} p={p}/>)}</div>}</main><footer>© {new Date().getFullYear()} Achadinhos Diários</footer></>
}
function ProductCard({p}){const d=discount(p.old_price,p.price);return <article className="card">{p.image_url?<img src={p.image_url} className="product-img"/>:<div className="no-img">📦</div>}<div className="card-body">{d&&<span className="discount">-{d}%</span>}<h3>{p.name}</h3>{p.description&&<p>{p.description}</p>}<div className="prices">{p.old_price&&<del>{money(p.old_price)}</del>}<strong>{money(p.price)}</strong></div><a className="offer" href={p.offer_url} target="_blank" rel="noreferrer">VER OFERTA →</a></div></article>}

function Auth({onLogin}){const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [busy,setBusy]=useState(false);const [err,setErr]=useState('');async function login(e){e.preventDefault();setBusy(true);setErr('');const {data,error}=await supabase.auth.signInWithPassword({email,password:pass});setBusy(false);if(error)return setErr(error.message);onLogin(data.session);}return <div className="auth-wrap"><div className="auth-card"><img src="/logo.jpg"/><h1>Painel Administrativo</h1><p>Entre para gerenciar os achadinhos.</p><form onSubmit={login}><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" required value={pass} onChange={e=>setPass(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="btn primary" disabled={busy}>{busy?'Entrando...':'Entrar no painel'}</button></form><Link to="/">← Voltar para a loja</Link></div></div>}

function Protected({children}){const [session,setSession]=useState(undefined);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe();},[]);if(session===undefined)return <div className="empty">Verificando acesso...</div>;if(!session)return <Auth onLogin={setSession}/>;return children;}

const blank={name:'',description:'',price:'',old_price:'',offer_url:'',image_url:'',active:true};
function Admin(){const [products,setProducts]=useState([]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState(null);const [file,setFile]=useState(null);const [saving,setSaving]=useState(false);const [msg,setMsg]=useState('');
 useEffect(()=>{load();},[]);async function load(){const {data}=await supabase.from('products').select('*').order('created_at',{ascending:false});setProducts(data||[]);}
 function reset(){setForm(blank);setEditing(null);setFile(null);setMsg('');}
 function edit(p){setEditing(p.id);setForm({...p,price:String(p.price??''),old_price:p.old_price==null?'':String(p.old_price)});setFile(null);window.scrollTo({top:0,behavior:'smooth'});}
 async function uploadImage(){if(!file)return form.image_url;const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl;}
 async function save(e){e.preventDefault();setSaving(true);setMsg('');try{const image=await uploadImage();const payload={name:form.name.trim(),description:form.description.trim(),price:Number(form.price),old_price:form.old_price?Number(form.old_price):null,offer_url:form.offer_url.trim(),image_url:image||null,active:!!form.active};let result;if(editing)result=await supabase.from('products').update(payload).eq('id',editing);else result=await supabase.from('products').insert(payload);if(result.error)throw result.error;setMsg('Produto salvo com sucesso!');reset();await load();}catch(e){setMsg('Erro: '+e.message)}finally{setSaving(false)}}
 async function remove(p){if(!confirm(`Excluir “${p.name}”?`))return;const {error}=await supabase.from('products').delete().eq('id',p.id);if(error)return setMsg('Erro: '+error.message);load();}
 async function toggle(p){const {error}=await supabase.from('products').update({active:!p.active}).eq('id',p.id);if(error)setMsg('Erro: '+error.message);else load();}
 return <><Header admin/><main className="admin"><div className="admin-head"><div><span className="pill"></span><h1>Painel de produtos</h1><p>Cadastre, edite e publique seus achadinhos.</p></div><Link className="btn ghost" to="/">Ver loja ↗</Link></div><section className="form-card"><h2>{editing?'Editar produto':'Novo produto'}</h2><form onSubmit={save} className="form-grid"><label>Nome do produto<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Preço atual<input required type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Preço antigo (opcional)<input type="number" min="0" step="0.01" value={form.old_price} onChange={e=>setForm({...form,old_price:e.target.value})}/></label><label>Link da oferta<input required type="url" placeholder="https://..." value={form.offer_url} onChange={e=>setForm({...form,offer_url:e.target.value})}/></label><label className="wide">Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Foto do produto<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/>{form.image_url&&!file&&<small>Foto atual cadastrada.</small>}</label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Publicar na loja</label><div className="actions"><button className="btn primary" disabled={saving}>{saving?'Salvando...':editing?'Salvar alterações':'Adicionar produto'}</button>{editing&&<button type="button" className="btn ghost" onClick={reset}>Cancelar</button>}</div></form>{msg&&<div className={msg.startsWith('Erro')?'error':'success'}>{msg}</div>}</section><section className="list-card"><div className="list-head"><h2>Produtos cadastrados</h2><span>{products.length} total</span></div><div className="table">{products.length===0?<div className="empty">Você ainda não cadastrou produtos.</div>:products.map(p=><div className="row" key={p.id}><div className="mini">{p.image_url?<img src={p.image_url}/>:<span>📦</span>}</div><div className="info"><b>{p.name}</b><span>{money(p.price)} · {p.active?'Publicado':'Oculto'}</span></div><button onClick={()=>toggle(p)} className="icon-btn">{p.active?'👁️':'🚫'}</button><button onClick={()=>edit(p)} className="icon-btn">✏️</button><button onClick={()=>remove(p)} className="icon-btn danger">🗑️</button></div>)}</div></section></main></>}

function App(){return <Routes><Route path="/" element={<PublicHome/>}/><Route path="/painel" element={<Protected><Admin/></Protected>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
